/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'scene-hotspots': SceneHotspot;
    'mariam-works': MariamWork;
    'sard-learning': SardLearning;
    'about-sard-awards': AboutSardAward;
    'about-sard-grants': AboutSardGrant;
    'team-members': TeamMember;
    galleries: Gallery;
    'contact-submissions': ContactSubmission;
    'about-sard-partners': AboutSardPartner;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'scene-hotspots': SceneHotspotsSelect<false> | SceneHotspotsSelect<true>;
    'mariam-works': MariamWorksSelect<false> | MariamWorksSelect<true>;
    'sard-learning': SardLearningSelect<false> | SardLearningSelect<true>;
    'about-sard-awards': AboutSardAwardsSelect<false> | AboutSardAwardsSelect<true>;
    'about-sard-grants': AboutSardGrantsSelect<false> | AboutSardGrantsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'about-sard-partners': AboutSardPartnersSelect<false> | AboutSardPartnersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'site-header': SiteHeader;
    'site-footer': SiteFooter;
    'latest-news-bar': LatestNewsBar;
    scene: Scene;
    'mariam-about': MariamAbout;
    'learning-about': LearningAbout;
    'sard-milestones-about': SardMilestonesAbout;
    'sard-vision-mission': SardVisionMission;
    'sard-production-about-hero': SardProductionAboutHero;
    'sard-writer-about-hero': SardWriterAboutHero;
    'contact-us': ContactUs;
  };
  globalsSelect: {
    'site-header': SiteHeaderSelect<false> | SiteHeaderSelect<true>;
    'site-footer': SiteFooterSelect<false> | SiteFooterSelect<true>;
    'latest-news-bar': LatestNewsBarSelect<false> | LatestNewsBarSelect<true>;
    scene: SceneSelect<false> | SceneSelect<true>;
    'mariam-about': MariamAboutSelect<false> | MariamAboutSelect<true>;
    'learning-about': LearningAboutSelect<false> | LearningAboutSelect<true>;
    'sard-milestones-about': SardMilestonesAboutSelect<false> | SardMilestonesAboutSelect<true>;
    'sard-vision-mission': SardVisionMissionSelect<false> | SardVisionMissionSelect<true>;
    'sard-production-about-hero': SardProductionAboutHeroSelect<false> | SardProductionAboutHeroSelect<true>;
    'sard-writer-about-hero': SardWriterAboutHeroSelect<false> | SardWriterAboutHeroSelect<true>;
    'contact-us': ContactUsSelect<false> | ContactUsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scene-hotspots".
 */
export interface SceneHotspot {
  id: string;
  labelEn: string;
  labelAr: string;
  descriptionEn?: string | null;
  descriptionAr?: string | null;
  x: number;
  y: number;
  xMobile?: number | null;
  yMobile?: number | null;
  targetPath: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mariam-works".
 */
export interface MariamWork {
  id: string;
  titleEn: string;
  titleAr: string;
  slug: string;
  year: number;
  directorEn: string;
  directorAr: string;
  posterEn: string | Media;
  posterAr: string | Media;
  media?:
    | {
        type?: ('image' | 'video') | null;
        thumbEn: string | Media;
        thumbAr: string | Media;
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  cast?:
    | {
        nameEn: string;
        nameAr: string;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-learning".
 */
export interface SardLearning {
  id: string;
  titleEn: string;
  titleAr: string;
  slug: string;
  subTitleEn?: string | null;
  subTitleAr?: string | null;
  posterEn: string | Media;
  posterAr?: (string | null) | Media;
  leftColumnEn: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  rightColumnEn?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  leftColumnAr: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  rightColumnAr?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cast?:
    | {
        nameEn: string;
        nameAr: string;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-sard-awards".
 */
export interface AboutSardAward {
  id: string;
  titleEn: string;
  titleAr: string;
  descriptionEn?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  imageEn?: (string | null) | Media;
  imageAr?: (string | null) | Media;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-sard-grants".
 */
export interface AboutSardGrant {
  id: string;
  sectionTitleEn: string;
  sectionTitleAr: string;
  descriptionEn?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items?:
    | {
        year: string;
        captionEn: string;
        captionAr?: string | null;
        detailsEn?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        detailsAr?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (string | null) | Media;
        isActive?: boolean | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string;
  nameEn: string;
  nameAr: string;
  photoEn: string | Media;
  photoAr?: (string | null) | Media;
  badgeIconEn?: (string | null) | Media;
  badgeIconAr?: (string | null) | Media;
  detailsEn: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  detailsAr: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  displayOn: ('aboutSard' | 'aboutMariam' | 'home' | 'portfolio')[];
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: string;
  titleEn: string;
  titleAr: string;
  /**
   * Use this slug in the frontend (e.g. about-sard-newest-production).
   */
  slug: string;
  isActive?: boolean | null;
  sectionTitleEn?: string | null;
  sectionTitleAr?: string | null;
  sectionDescriptionEn?: string | null;
  sectionDescriptionAr?: string | null;
  items?:
    | {
        titleEn: string;
        titleAr: string;
        descriptionEn?: string | null;
        descriptionAr?: string | null;
        backgroundEn: string | Media;
        backgroundAr?: (string | null) | Media;
        directorEn?: string | null;
        directorAr?: string | null;
        /**
         * YouTube link or direct mp4/webm link. If empty, play button can be hidden.
         */
        videoUrl?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  company?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-sard-partners".
 */
export interface AboutSardPartner {
  id: string;
  sectionTitleEn: string;
  sectionTitleAr: string;
  items?:
    | {
        logo: string | Media;
        name?: string | null;
        isActive?: boolean | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'scene-hotspots';
        value: string | SceneHotspot;
      } | null)
    | ({
        relationTo: 'mariam-works';
        value: string | MariamWork;
      } | null)
    | ({
        relationTo: 'sard-learning';
        value: string | SardLearning;
      } | null)
    | ({
        relationTo: 'about-sard-awards';
        value: string | AboutSardAward;
      } | null)
    | ({
        relationTo: 'about-sard-grants';
        value: string | AboutSardGrant;
      } | null)
    | ({
        relationTo: 'team-members';
        value: string | TeamMember;
      } | null)
    | ({
        relationTo: 'galleries';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'about-sard-partners';
        value: string | AboutSardPartner;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scene-hotspots_select".
 */
export interface SceneHotspotsSelect<T extends boolean = true> {
  labelEn?: T;
  labelAr?: T;
  descriptionEn?: T;
  descriptionAr?: T;
  x?: T;
  y?: T;
  xMobile?: T;
  yMobile?: T;
  targetPath?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mariam-works_select".
 */
export interface MariamWorksSelect<T extends boolean = true> {
  titleEn?: T;
  titleAr?: T;
  slug?: T;
  year?: T;
  directorEn?: T;
  directorAr?: T;
  posterEn?: T;
  posterAr?: T;
  media?:
    | T
    | {
        type?: T;
        thumbEn?: T;
        thumbAr?: T;
        videoUrl?: T;
        id?: T;
      };
  cast?:
    | T
    | {
        nameEn?: T;
        nameAr?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-learning_select".
 */
export interface SardLearningSelect<T extends boolean = true> {
  titleEn?: T;
  titleAr?: T;
  slug?: T;
  subTitleEn?: T;
  subTitleAr?: T;
  posterEn?: T;
  posterAr?: T;
  leftColumnEn?: T;
  rightColumnEn?: T;
  leftColumnAr?: T;
  rightColumnAr?: T;
  cast?:
    | T
    | {
        nameEn?: T;
        nameAr?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-sard-awards_select".
 */
export interface AboutSardAwardsSelect<T extends boolean = true> {
  titleEn?: T;
  titleAr?: T;
  descriptionEn?: T;
  descriptionAr?: T;
  imageEn?: T;
  imageAr?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-sard-grants_select".
 */
export interface AboutSardGrantsSelect<T extends boolean = true> {
  sectionTitleEn?: T;
  sectionTitleAr?: T;
  descriptionEn?: T;
  descriptionAr?: T;
  items?:
    | T
    | {
        year?: T;
        captionEn?: T;
        captionAr?: T;
        detailsEn?: T;
        detailsAr?: T;
        image?: T;
        isActive?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  nameEn?: T;
  nameAr?: T;
  photoEn?: T;
  photoAr?: T;
  badgeIconEn?: T;
  badgeIconAr?: T;
  detailsEn?: T;
  detailsAr?: T;
  displayOn?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  titleEn?: T;
  titleAr?: T;
  slug?: T;
  isActive?: T;
  sectionTitleEn?: T;
  sectionTitleAr?: T;
  sectionDescriptionEn?: T;
  sectionDescriptionAr?: T;
  items?:
    | T
    | {
        titleEn?: T;
        titleAr?: T;
        descriptionEn?: T;
        descriptionAr?: T;
        backgroundEn?: T;
        backgroundAr?: T;
        directorEn?: T;
        directorAr?: T;
        videoUrl?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  company?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-sard-partners_select".
 */
export interface AboutSardPartnersSelect<T extends boolean = true> {
  sectionTitleEn?: T;
  sectionTitleAr?: T;
  items?:
    | T
    | {
        logo?: T;
        name?: T;
        isActive?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header".
 */
export interface SiteHeader {
  id: string;
  logoLarge: string | Media;
  logoLargeAlt?: string | null;
  logoSmall?: (string | null) | Media;
  logoSmallAlt?: string | null;
  links?:
    | {
        label: {
          en: string;
          ar: string;
        };
        /**
         * Example: /about-sard (Do NOT include /en or /ar)
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Icons will show in the menu footer
   */
  social?:
    | {
        label?: string | null;
        href: string;
        icon: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer".
 */
export interface SiteFooter {
  id: string;
  logoLeftEn?: (string | null) | Media;
  logoLeftAr?: (string | null) | Media;
  logoLeftAltEn?: string | null;
  logoLeftAltAr?: string | null;
  logoRightEn?: (string | null) | Media;
  logoRightAr?: (string | null) | Media;
  logoRightAltEn?: string | null;
  logoRightAltAr?: string | null;
  links?:
    | {
        labelEn: string;
        labelAr: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyrightEn: string;
  copyrightAr: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "latest-news-bar".
 */
export interface LatestNewsBar {
  id: string;
  enabled?: boolean | null;
  accentColor?: string | null;
  items: {
    isActive?: boolean | null;
    order?: number | null;
    thumb?: (string | null) | Media;
    dateText?: string | null;
    titleEn: string;
    titleAr: string;
    summaryEn?: string | null;
    summaryAr?: string | null;
    href?: string | null;
    newTab?: boolean | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scene".
 */
export interface Scene {
  id: string;
  title?: string | null;
  backgroundImageEn: string | Media;
  backgroundImageAr?: (string | null) | Media;
  hintEn: string;
  hintAr: string;
  canvasWidthLg?: number | null;
  canvasWidthMd?: number | null;
  canvasWidthSm?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mariam-about".
 */
export interface MariamAbout {
  id: string;
  portrait: string | Media;
  portraitAr?: (string | null) | Media;
  allAboutLabel?: {
    en?: string | null;
    ar?: string | null;
  };
  displayName: {
    en: string;
    ar: string;
  };
  leftColumn: {
    en: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ar: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  rightColumn?: {
    en?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    ar?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-about".
 */
export interface LearningAbout {
  id: string;
  portrait: string | Media;
  portraitAr?: (string | null) | Media;
  allAboutLabel?: {
    en?: string | null;
    ar?: string | null;
  };
  displayName: {
    en: string;
    ar: string;
  };
  leftColumn: {
    en: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ar: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  rightColumn?: {
    en?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    ar?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-milestones-about".
 */
export interface SardMilestonesAbout {
  id: string;
  portrait: string | Media;
  portraitAr?: (string | null) | Media;
  allAboutLabel?: {
    en?: string | null;
    ar?: string | null;
  };
  displayName: {
    en: string;
    ar: string;
  };
  leftColumn: {
    en: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ar: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  rightColumn: {
    en: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ar: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-vision-mission".
 */
export interface SardVisionMission {
  id: string;
  sectionTitleEn: string;
  sectionTitleAr: string;
  vision: {
    titleEn: string;
    titleAr: string;
    bodyEn: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    bodyAr: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  mission: {
    titleEn: string;
    titleAr: string;
    bodyEn: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    bodyAr: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  values: {
    titleEn: string;
    titleAr: string;
    bodyEn: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    bodyAr: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-production-about-hero".
 */
export interface SardProductionAboutHero {
  id: string;
  portrait: string | Media;
  portraitAr?: (string | null) | Media;
  allAboutLabel?: {
    en?: string | null;
    ar?: string | null;
  };
  displayName: {
    en: string;
    ar: string;
  };
  leftColumn: {
    en: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ar: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  rightColumn?: {
    en?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    ar?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-writer-about-hero".
 */
export interface SardWriterAboutHero {
  id: string;
  portrait: string | Media;
  portraitAr?: (string | null) | Media;
  allAboutLabel?: {
    en?: string | null;
    ar?: string | null;
  };
  displayName: {
    en: string;
    ar: string;
  };
  leftColumn: {
    en: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ar: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  rightColumn?: {
    en?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    ar?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us".
 */
export interface ContactUs {
  id: string;
  en: {
    pageTitle: string;
    contactLines: {
      phoneLabel: string;
      phoneValue: string;
      emailLabel: string;
      emailValue: string;
    };
    locationCard: {
      title: string;
      subtitle: string;
      /**
       * Google Maps EMBED url (starts with https://www.google.com/maps/embed?pb=...)
       */
      mapEmbedUrl: string;
      mapHeight: number;
    };
    formCard: {
      title: string;
      endpoint: string;
      nameLabel: string;
      namePlaceholder: string;
      emailLabel: string;
      emailPlaceholder: string;
      subjectLabel: string;
      subjectPlaceholder: string;
      messageLabel: string;
      messagePlaceholder: string;
      requiredError: string;
      successMessage: string;
      genericError: string;
      networkError: string;
      sendButton: string;
      sendingButton: string;
    };
  };
  ar: {
    pageTitle: string;
    contactLines: {
      phoneLabel: string;
      phoneValue: string;
      emailLabel: string;
      emailValue: string;
    };
    locationCard: {
      title: string;
      subtitle: string;
      mapEmbedUrl: string;
      mapHeight: number;
    };
    formCard: {
      title: string;
      endpoint: string;
      nameLabel: string;
      namePlaceholder: string;
      emailLabel: string;
      emailPlaceholder: string;
      subjectLabel: string;
      subjectPlaceholder: string;
      messageLabel: string;
      messagePlaceholder: string;
      requiredError: string;
      successMessage: string;
      genericError: string;
      networkError: string;
      sendButton: string;
      sendingButton: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header_select".
 */
export interface SiteHeaderSelect<T extends boolean = true> {
  logoLarge?: T;
  logoLargeAlt?: T;
  logoSmall?: T;
  logoSmallAlt?: T;
  links?:
    | T
    | {
        label?:
          | T
          | {
              en?: T;
              ar?: T;
            };
        href?: T;
        id?: T;
      };
  social?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer_select".
 */
export interface SiteFooterSelect<T extends boolean = true> {
  logoLeftEn?: T;
  logoLeftAr?: T;
  logoLeftAltEn?: T;
  logoLeftAltAr?: T;
  logoRightEn?: T;
  logoRightAr?: T;
  logoRightAltEn?: T;
  logoRightAltAr?: T;
  links?:
    | T
    | {
        labelEn?: T;
        labelAr?: T;
        href?: T;
        id?: T;
      };
  copyrightEn?: T;
  copyrightAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "latest-news-bar_select".
 */
export interface LatestNewsBarSelect<T extends boolean = true> {
  enabled?: T;
  accentColor?: T;
  items?:
    | T
    | {
        isActive?: T;
        order?: T;
        thumb?: T;
        dateText?: T;
        titleEn?: T;
        titleAr?: T;
        summaryEn?: T;
        summaryAr?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scene_select".
 */
export interface SceneSelect<T extends boolean = true> {
  title?: T;
  backgroundImageEn?: T;
  backgroundImageAr?: T;
  hintEn?: T;
  hintAr?: T;
  canvasWidthLg?: T;
  canvasWidthMd?: T;
  canvasWidthSm?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mariam-about_select".
 */
export interface MariamAboutSelect<T extends boolean = true> {
  portrait?: T;
  portraitAr?: T;
  allAboutLabel?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  displayName?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  leftColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  rightColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-about_select".
 */
export interface LearningAboutSelect<T extends boolean = true> {
  portrait?: T;
  portraitAr?: T;
  allAboutLabel?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  displayName?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  leftColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  rightColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-milestones-about_select".
 */
export interface SardMilestonesAboutSelect<T extends boolean = true> {
  portrait?: T;
  portraitAr?: T;
  allAboutLabel?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  displayName?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  leftColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  rightColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-vision-mission_select".
 */
export interface SardVisionMissionSelect<T extends boolean = true> {
  sectionTitleEn?: T;
  sectionTitleAr?: T;
  vision?:
    | T
    | {
        titleEn?: T;
        titleAr?: T;
        bodyEn?: T;
        bodyAr?: T;
      };
  mission?:
    | T
    | {
        titleEn?: T;
        titleAr?: T;
        bodyEn?: T;
        bodyAr?: T;
      };
  values?:
    | T
    | {
        titleEn?: T;
        titleAr?: T;
        bodyEn?: T;
        bodyAr?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-production-about-hero_select".
 */
export interface SardProductionAboutHeroSelect<T extends boolean = true> {
  portrait?: T;
  portraitAr?: T;
  allAboutLabel?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  displayName?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  leftColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  rightColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sard-writer-about-hero_select".
 */
export interface SardWriterAboutHeroSelect<T extends boolean = true> {
  portrait?: T;
  portraitAr?: T;
  allAboutLabel?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  displayName?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  leftColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  rightColumn?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us_select".
 */
export interface ContactUsSelect<T extends boolean = true> {
  en?:
    | T
    | {
        pageTitle?: T;
        contactLines?:
          | T
          | {
              phoneLabel?: T;
              phoneValue?: T;
              emailLabel?: T;
              emailValue?: T;
            };
        locationCard?:
          | T
          | {
              title?: T;
              subtitle?: T;
              mapEmbedUrl?: T;
              mapHeight?: T;
            };
        formCard?:
          | T
          | {
              title?: T;
              endpoint?: T;
              nameLabel?: T;
              namePlaceholder?: T;
              emailLabel?: T;
              emailPlaceholder?: T;
              subjectLabel?: T;
              subjectPlaceholder?: T;
              messageLabel?: T;
              messagePlaceholder?: T;
              requiredError?: T;
              successMessage?: T;
              genericError?: T;
              networkError?: T;
              sendButton?: T;
              sendingButton?: T;
            };
      };
  ar?:
    | T
    | {
        pageTitle?: T;
        contactLines?:
          | T
          | {
              phoneLabel?: T;
              phoneValue?: T;
              emailLabel?: T;
              emailValue?: T;
            };
        locationCard?:
          | T
          | {
              title?: T;
              subtitle?: T;
              mapEmbedUrl?: T;
              mapHeight?: T;
            };
        formCard?:
          | T
          | {
              title?: T;
              endpoint?: T;
              nameLabel?: T;
              namePlaceholder?: T;
              emailLabel?: T;
              emailPlaceholder?: T;
              subjectLabel?: T;
              subjectPlaceholder?: T;
              messageLabel?: T;
              messagePlaceholder?: T;
              requiredError?: T;
              successMessage?: T;
              genericError?: T;
              networkError?: T;
              sendButton?: T;
              sendingButton?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}